stages:
  - build
  - test
  - cleanup

before_script:
  - sudo chown -R gitlab-runner:gitlab-runner .

build:
  stage: build
  tags: [storage-manager]
  script:
    - echo "Done."

test:
  stage: test
  tags: [storage-manager]
  script:
    - echo "Starting storage manager unit tests"
    - sudo -u gitlab-runner bash -c 'cd ./src/build && docker-compose -f docker-compose-test.yml up --remove-orphans --force-recreate --exit-code-from edgeflex-storagemanager-test'
    - cd src/build && sudo chown -R -v gitlab-runner:gitlab-runner ./reports/
    - echo "Done."

cleanup:
  stage: cleanup
  tags: [storage-manager]
  script:
    - echo "Cleaning up after tests."
    - sudo chown -R -v gitlab-runner:gitlab-runner src/build/reports/
    - sudo rm -rf src/build/reports/*
    - cd ./src/build && docker-compose -f docker-compose-test.yml down --rmi local -v --remove-orphans
    - docker network rm edgeflex-network || true
    - echo "Done."
