stages:
  - build
  - test
  - cleanup

before_script:
  - sudo chown -R gitlab-runner:gitlab-runner .

build:
  stage: build
  tags: [storage-manager]
  script:
    - docker network create edgeflex-network || true
    - docker build -t edgeflex-base-image -f build/Dockerfile .
    - echo "Done."

test:
  stage: test
  tags: [storage-manager]
  script:
    - echo "Starting storage manager unit tests"
    - sudo -u gitlab-runner bash -c 'docker-compose -f build/docker-compose-test.yml up --remove-orphans --force-recreate --exit-code-from edgeflex-storagemanager-test'
    - cd build && sudo chown -R -v gitlab-runner:gitlab-runner ./reports/
    - echo "Done."

cleanup:
  when: always
  stage: cleanup
  tags: [storage-manager]
  script:
    - echo "Cleaning up after tests."
    - sudo chown -R -v gitlab-runner:gitlab-runner build/reports/
    - sudo rm -rf build/reports/*
    - docker-compose -f build/docker-compose-test.yml down --rmi local -v --remove-orphans
    - docker network rm edgeflex-network || true
    - echo "Done."
